In [3]:
import numpy as np

In [5]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
b=np.zeros(10)
b[:]=5
b

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [15]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [17]:
np.arange(10,52,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [21]:
a=np.arange(0,9)
a.resize(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.random.rand(1)

array([0.82887835])

In [31]:
np.random.randn(25)

array([ 1.97914318, -0.29127963,  0.43803985, -0.34125052,  0.22518782,
       -2.01177361, -0.66332336, -0.76645744,  1.52763896,  0.51221419,
        1.72255492, -1.63024767, -0.15664209,  1.47297949,  0.52514804,
        0.53276401,  0.72275573, -1.07106839, -0.11360094, -0.95187705,
       -0.55159957, -1.22843442, -0.45006245, -1.67305065,  0.02375892])

In [43]:
c=np.linspace(0,1,100)
c.resize(10,10)
c

array([[0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
        0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909],
       [0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
        0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919],
       [0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
        0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929],
       [0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
        0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939],
       [0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
        0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949],
       [0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
        0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ],
       [0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
        0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ],
       [0.70707071, 0.71717172, 0.7272727

In [41]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [108]:
mat=np.arange(12,24).reshape(3,4)
mat

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [80]:
mat[2,0]

np.int64(20)

In [94]:
mat=np.arange(2,13,5).reshape(3,1)
mat

array([[ 2],
       [ 7],
       [12]])

In [90]:
np.arange(21,26)

array([21, 22, 23, 24, 25])

In [95]:
mat=np.arange(16,26).reshape(2,5)
mat

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [121]:
mat=np.arange(1,26).reshape(5,5)
int(mat.sum())

325

In [120]:
float(mat.std())

7.211102550927978

In [122]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])